# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

def content_generator
	content = ""
	rand(3..5).times do
		content += Faker::Hipster.paragraph(5, false, 4) + "<br>"
	end
	content
end

Movie.create(name: "Spotlight", imdb_url: "http://www.imdb.com/title/tt1895587/", img_url: "http://thetipsyverse.com/wp-content/uploads/2015/11/Spotlight-Movie-Review-1.jpg", movie_image: File.new("#{Rails.root}/public/spotlight.jpg"))

Movie.create(name: "Birdman or (The Unexpected Virtue of Ignorance)", imdb_url: "http://www.imdb.com/title/tt2562232/", img_url: "http://www.wired.com/wp-content/uploads/2014/10/Birdman.jpg",movie_image: File.new("#{Rails.root}/public/birdman.jpg"))

Movie.create(name: "12 Years a Slave", imdb_url: "http://www.imdb.com/title/tt2024544/", img_url: "http://ia.media-imdb.com/images/M/MV5BMjExMTEzODkyN15BMl5BanBnXkFtZTcwNTU4NTc4OQ@@._V1_SX640_SY720_.jpg",movie_image: File.new("#{Rails.root}/public/12yearsaslave.jpg"))

Movie.create(name: "Argo", imdb_url: "http://www.imdb.com/title/tt1024648/", img_url: "http://www.revelationsradionews.com/wp-content/uploads/2013/02/01_argo_ipad.jpg",movie_image: File.new("#{Rails.root}/public/argo.jpg"))

Movie.create(name: "The Artist", imdb_url: "http://www.imdb.com/title/tt1655442/", img_url: "https://generationfilm.files.wordpress.com/2011/11/artist_primary.jpg",movie_image: File.new("#{Rails.root}/public/theartist.jpg"))

Critic.create(username: "Mike Busch", password: "password", email: "radical_saint@yahoo.net", profile_image: File.new("#{Rails.root}/public/mike.jpg"))

Critic.create(username: "Duke Green", password: "password", email: "turkishdelight44@comcast.net", profile_image: File.new("#{Rails.root}/public/duke.jpg"))

Critic.create(username: "Casey Cumbow", password: "password", email: "awalkonthewordside@aol.com", profile_image: File.new("#{Rails.root}/public/casey.jpg"))

Critic.create(username: "Alyssa Diaz", password: "password", email: "squidwordwasright@boosh.org", profile_image: File.new("#{Rails.root}/public/alyssa.jpg"))

Critic.create(username: "Matt Baker", password: "password", email: "donttellmomthebabysittersisdead@gmail.com", profile_image: File.new("#{Rails.root}/public/matt.jpg"))

Critic.create(username: "Maurice Rabb", password: "password", email: "maurice@gmail.com", profile_image: File.new("#{Rails.root}/public/maurice.jpg"))

Event.create(pub_date: Date.yesterday, name: "Everyone but Baker.", creator: Critic.find(1), movie: Movie.find(1))

Event.create(pub_date: Date.today, name: "No critic left behind", creator: Critic.find(2), movie: Movie.find(2))

Event.create(pub_date: Date.today, name: "Another bummer movie", creator: Critic.find(3), movie: Movie.find(3))

Event.create(pub_date: Date.today, name: "Ben Affleck, Director?", creator: Critic.find(4), movie: Movie.find(4))

Event.create(pub_date: Date.today + 30, name: "Black and white is back!", creator: Critic.find(5), movie: Movie.find(5))


Review.create(critic: Critic.find(1), event: Event.find(1), content: "Spotlight is a movie of clarity and force: the true story of the Boston Globe’s 'Spotlight' team and its 2002 campaign to investigate a church cover-up of child abuse by Catholic priests.

  Its value was obvious at the Venice film festival last year, but it has grown in my mind since: what seemed like a plodding pace is actually a shrewd approximation of the steady drumbeat that effective reporting creates. This is what the police work of investigative journalism looks like: the documents, the phone calls, the pre-web clippings, the expense of shoe leather in going out to interview people who don’t want to be interviewed. Spotlight doesn’t have the sensational thrills of Alan J Pakula’s All the President’s Men (1976), or for that matter David Fincher’s Zodiac (2007). And there are a few journo cliches. But it has the sinew of a really good procedural, underpinned by genuine moral outrage.

  Michael Keaton plays veteran reporter Walter “Robby” Robinson, working alongside hot-tempered Mike Rezendes, played by Mark Ruffalo, and Sacha Pfeiffer, played by Rachel McAdams, who has an extraordinary scene when she persuades an abuser-priest to come to the door and talk. Boston was a clubbable world in which a smile on the golf course, or a pat on the back and a meaningful look at the church social was enough to enforce silence. It takes a new editor, Marty Baron (Liev Schreiber) – non-Boston, non-Catholic – to shake things up and insist on doing the child abuse story properly, and paradoxically reveal the paper’s own former shortcomings.

  The film has real insights to offer: the cast powerfully convey the journalists’ horror at realising the abuse stretches back decades or even centuries and also how abuse is as much about power as sex and that homosexuality is beside the point: the abusers have evolved the choice of boy victims because boys are reticent, more likely to swallow their shame and not speak out. A powerful story.", ratings: "#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(30..50)}")

Review.create(critic: Critic.find(2), event: Event.find(1), content: "“The city flourishes when its great institutions work together,” says the cardinal to the newspaper editor during a friendly chat in the rectory. The city in question is Boston. The cardinal is Bernard F. Law and the editor, newly arrived at The Boston Globe from The Miami Herald, is Martin Baron. He politely dissents from the cardinal’s vision of civic harmony, arguing that the paper should stand alone.

  Their conversation, which takes place early in “Spotlight,” sets up the film’s central conflict. Encouraged by Baron, a small group of reporters at The Globe will spend the next eight months (and the next two hours) digging into the role of the Boston archdiocese in covering up the sexual abuse of children by priests. But the image of two prominent men talking quietly behind closed doors — Law is played with orotund charm by Len Cariou, Baron with sphinxlike self-containment by Liev Schreiber — haunts this somber, thrilling movie and crystallizes its major concern, which is the way power operates in the absence of accountability. When institutions convinced of their own greatness work together, what usually happens is that the truth is buried and the innocent suffer. Breaking that pattern of collaboration is not easy. Challenging deeply entrenched, widely respected authority can be very scary.

Directed by Tom McCarthy from a script he wrote with Josh Singer and based closely on recent history, “Spotlight” is a gripping detective story and a superlative newsroom drama, a solid procedural that tries to confront evil without sensationalism. Taking its name from the investigative team that began pursuing the sex-abuse story in 2001, the film focuses on both the human particulars and the larger political contours of the scandal and its uncovering.

We spend most of our time with the Spotlight staff. Their supervising editor, Walter Robinson (known as Robby and played by an extra-flinty Michael Keaton), has a classically blunt, skeptical newsman style, but he’s also part of Boston’s mostly Roman Catholic establishment. He rubs shoulders with an unctuous church P.R. guy (Paul Guilfoyle) and plays golf with a well-connected lawyer (Jamey Sheridan) who handled some of the archdiocese’s unsavory business. The reporters working for Robby — Sacha Pfeiffer (Rachel McAdams), Mike Rezendes (Mark Ruffalo) and Matt Carroll (Brian d’Arcy James) — come from Catholic backgrounds, and have their own mixed feelings about what they’re doing.

Mr. McCarthy, who played a rotten reporter on the last season of “The Wire,” views journalists primarily through the lens of their work. He follows Pfeiffer as she interviews survivors, Rezendes as he wrangles a zealous lawyer (Stanley Tucci) and Carroll as he digs into long-hidden records, including articles buried in the newspaper’s archives. Though the film, like the Spotlight articles, avoids euphemism in discussing the facts of child rape, it also avoids exploitative flashbacks, balancing attention to individual cases with a sense of pervasive, invisible corruption. Baron urges the reporters to focus on the systemic dimensions of the story, and “Spotlight” does the same. As the number of victims and predators increases, and as it becomes clear that Law and others knew what was happening and protected the guilty, shock and indignation are replaced by a deeper sense of moral horror.", ratings: "#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(30..50)}")

Review.create(critic: Critic.find(3), event: Event.find(1), content: "In 2002, the Boston Globe published an explosive series of articles about the decades-long scandal of child sexual abuse within the Catholic Church, involving 70 local priests, more than 1,000 victims and the collusion of Cardinal Bernard Law in covering up the crimes. As a piece of journalism, it was a barnburner, one that garnered the paper a Pulitzer Prize the following year for its airing of truths long suppressed within the Catholic hierarchy.

Named for the team that reported and wrote the Globe stories, the movie “Spotlight” chronicles the shoe-leather investigation conducted over several months prior to publication. But before we get to the review, a few disclosures are in order: For one, the film’s chief protagonist, Globe editor Marty Baron, is now executive editor of The Washington Post.

For another — and perhaps even more important — the film depicts a profession this reviewer has pursued for 30 years and held in near-worshipful esteem for far longer. For journalists, watching “Spotlight’s” meticulous portrayal of their vocation is a surpassingly gratifying experience, one that former Baltimore Sun reporter David Simon, at the film’s local premiere in September, only half-facetiously compared to watching porn.

With “Spotlight,” director Tom McCarthy has fulfilled his first duty, which is to create a world that is utterly, convincingly immersive, down to the last granular detail. After a brief prologue set in the 1970s, the film opens in 2001 with a “caking,” an all-too-familiar newsroom ritual whereby departing staffers are celebrated with a heavily frosted sheet cake and some colorful war stories. Having nailed that scene — and its attendant whiff of economic insecurity — with anthropological care, McCarthy proceeds to get everything else uncannily right, from the overstarched shirts and pleated khakis worn by the Globe’s male reporters to the drudgery of looking up old clips and cranking microfilm. It’s not a stretch to suggest that “Spotlight” is the finest newspaper movie of its era, joining “Citizen Kane” and “All the President’s Men” in the pantheon of classics of the genre.

In its precision, modesty and restraint, “Spotlight” even does its most famous predecessors one better. McCarthy and his fellow screenwriter, Josh Singer, did their own reporting to create the film’s script, revisiting the reporters’ methods and even breaking a crucial piece of news of their own, revealing that the Globe missed a chance to advance the abuse story as far back as 1993. If “Citizen Kane” was a monumental narrative of operatic scope and visual ambition, and “All the President’s Men” a tautly paranoid thriller attuned to the dawning cynicism of its time, “Spotlight” has achieved something far more difficult, marshalling a pure, unadorned style in the service of a story that rejects mythologizing in favor of disciplined, level-eyed candor.", ratings: "#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(30..50)}")

Review.create(critic: Critic.find(4), event: Event.find(1), content: "There's no higher compliment to pay this steadily riveting, quietly devastating take on investigative journalism than to say Spotlight gets it right. So did the Spotlight team on The Boston Globe when, in 2002, it published nearly 600 articles on child sex-abuse allegations against Catholic priests and the church cover-ups that followed. The team won a Pulitzer for its scalding exposé. And right now the film is the predictive favorite to win the Best Picture Oscar. But awards are merely icing on a cake whose candles glow in tribute to long-form print journalism, now fading in the digital fog of budget cuts, reduced resources and click-bait news cycles.

Bravo to director Tom McCarthy (The Station Agent, Win Win, The Visitor), who wrote the richly detailed script with Josh Singer (The Fifth Estate). There's not an ounce of Hollywood bullshit in it. Our eyes and ears are the Spotlight team, played by exceptional actors who could not be better or more fully committed.

Michael Keaton is in peak form as Spotlight editor Walter 'Robby' Robinson, a stickler who is tough on reporters Michael Rezendes (Mark Ruffalo) and Sacha Pfeiffer (Rachel McAdams) and researcher Matt Carroll (Brian d'Arcy James). Robinson is skeptical that his newspaper, whose readers and staffers are largely Irish-Catholic, can tackle the Boston Archdiocese. Caution also guides Globe deputy managing editor Ben Bradlee Jr. (John Slattery), whose father, Washington Post editor Ben Bradlee, risked his job on the Watergate coverage.

The kick in the ass for Spotlight comes from an outsider: Marty Baron (a terrific Liev Schreiber), the paper's new top editor, a Floridian and the first Jew to call the shots at the Globe. Baron rightfully suspects a conspiracy and turns Spotlight loose. McCarthy and camera wizard Masanobu Takayanagi track the grinding work of real reporting. As Carroll, the excellent James digs into sealed records of priests whose crimes are swept aside. Political, social and legal systems are found complicit, including plaintiffs' lawyer Eric MacLeish (Billy Crudup) and Cardinal Bernard Law (Len Cariou). McAdams, sharp and sympathetic, shows us how Pfeiffer draws out details from victims whose childhoods meant sucking the dick of a priest who says he's had a bad day. And Ruffalo is a marvel of purpose as Rezendes hounds attorney Mitchell Garabedian (Stanley Tucci) for access to survivors of sex abuse.

It's these survivors who give Spotlight its beating heart. Roiling emotions are also felt among reporters who desperately want to get the story right and just as desperately want to get it first. That tension makes for an insanely gripping high-wire act and the year's most thrilling detective story. These reporters are jittery obsessives who put their lives on hold for a story they believe in. Do they get off on it? You bet. They're hardcore guardians of an endangered galaxy. And heroes, in my book. At times, it's hard not to choke up, but Spotlight refuses to wallow in nostalgia. This landmark film takes a clear-eyed look at the digital future and honors the one constant that journalism needs to stay alive and relevant: a fighting spirit.", ratings: "#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(30..50)}")

Review.create(critic: Critic.find(1), event: Event.find(2), content: "In Birdman or (The Unexpected Virtue of Ignorance), Michael Keaton plays former blockbuster movie star Riggan Thomson – remembered best for portraying comic book hero Birdman on the big screen (back in the 1990s). Fast forward two decades and Thomson is no longer a hot Hollywood commodity. Broke, separated from his wife (Amy Ryan), estranged from his rebellious daughter (Emma Stone), and forgotten by his once adoring fans, Thomson sets out to prove that he’s not just a washed up hack – opting to write, direct, and star in a Broadway show based on the Raymond Carver story 'What We Talk About When We Talk About Love'.

However, when Thomson is unhappy with the actor cast as Nick in the production (Jeremy Shamos), he makes a last minute replacement – auditioning critically acclaimed stage performer Mike Shiner (Edward Norton) to take over the part. Impressed by Shiner’s sincerity (and method acting approach), Thomson hires the quirky thespian less than 24 hours prior to the first preview performance of What We Talk About When We Talk About Love. However, when Shiner makes a scene during his first public rehearsal, Thomson is thrown into a spiral of self-doubt and fear – second-guessing his own talent, personal relationships, career choices, and begging the question: will audiences even be willing to love him again?

Birdman was written and directed by Mexican filmmaker Alejandro González Iñárritu – known to American audiences for 21 Grams and Babel. Despite marketing for the film, that positions it as a black comedy riff on current comic book movie trends, Birdman is much more in keeping with Iñárritu’s previous works – an art house exploration of imperfect people struggling to navigate our (often) cruel and fickle world. To that end, Birdman is a resounding success with great performances, mesmerizing cinematography, and thought-provoking thematic threads that play on both Carver’s story and pop culture to moving effect. That said, those anticipating a heavy dose of Keaton with a beak and armored wings could be underwhelmed, and feel a bit misled, by the amount of Birman in the actual film.

As indicated, while the Birdman trailers and print materials have positioned Iñárritu’s latest movie as counter-programming to Marvel and DC’s burgeoning cinematic universes, not to mention a meta-commentary on Keaton’s own history in the Batsuit, the actual story is focused on more personal matters: troubled relationships, artistic integrity, Broadway versus Hollywood, and the true definition of love. Birdman is about a father, husband, lover, business partner, and actor – not a superhero. Instead of an active plot point, Birdman is a shadowy figure from Thomson’s past – one that, above all else, haunts him (as a voice to his self-loathing). He’s a shoulder devil, rarely seen but a gripping source of temptation and self-destruction when the actor is vulnerable. The interplay between Thomson and Birdman charts a journey of risk and rejection – along with the pitfalls that accompany personal ambition and sincere attempts at artistry.", ratings: "#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(30..50)}")

Review.create(critic: Critic.find(2), event: Event.find(2), content: "I'm jazzed by every tasty, daring, devastating, howlingly funny, how'd-they-do-that minute in Birdman. Like all movies that soar above the toxic clouds of Hollywood formula and defy death at the box office, Alejandro G. Iñárritu's cinematic whirlwind will bring out the haters. They can all go piss off. Birdman is a volcano of creative ideas in full eruption. Buy a ticket and brace yourself.

The short take on Birdman is that it's a showbiz satire. Yeah, like Pulp Fiction is just a crime story. We're talking reinvention here. Michael Keaton, in a potent, pinballing tour de force, plays Riggan Thomson, an actor who's fallen on hard times since playing the superhero Birdman in a trilogy of blockbusters. Sound familiar? It should. After two acclaimed turns as the Caped Crusader in Tim Burton's Batman films, Keaton knows from what he's acting. He knows what it's like to fall short of the gold ring he once caught. Riggan's creative way back in is to make his Broadway debut by writing, directing and starring in What We Talk About When We Talk About Love, a short story by the extolled Raymond Carver. It seems Carver caught the young Riggan onstage years back and sent a note on a cocktail napkin that said, 'Thank you for an honest performance. Ray Carver.''

So there's Riggan trying to be honest again by walking the tightrope of Broadway, where vultures make a meal of movie stars. It's old news. But as filtered through the poet's eye of this risk-taking Mexican visionary (Amores Perros, 21 Grams, Babel, Biutiful) and his co-screenwriters, Nicolás Giacobone, Alexander Dinelaris Jr. and Armando Bo, we see things fresh. As suggested by the film's subtitle, The Unexpected Virtue of Ignorance, blundering can be bliss.

The key to Birdman is in the visuals, gloriously executed by camera genius Emmanuel Lubezki, an Oscar winner for Gravity, to give us the feeling that the film is unfolding in one sinuous, continuous take. Lubezki's work is breathtaking, especially for the way it allows the film to veer from reality to illusion and back again with no break. So when Riggan flies above Manhattan and shoots flame balls from his fingers, we too are living with the crazy-ass visions in his head. Hell, we first see Riggan levitating in his dressing room and debating with the voice of Birdman (Keaton in a lower register), who tells him he's too good for these theater pussies.

That leads to the introductions of other characters, all acted to perfection and all stressing out Riggan as he seesaws between narcissism and self-doubt. It's great to see how beautifully Zach Galifianakis plays it straight and true as Riggan's loyal producer. Naomi Watts excels as an actress in the play, as does Andrea Riseborough as the actress Riggan is shagging and Amy Ryan as the ex-wife who tries to restore balance to a conflicted man.

Besides Keaton, who digs deep and delivers the best performance of his career, there is award-caliber work from Edward Norton as a volatile actor who drives Riggan nuts, mostly because his talent is as big as his ego. And a never-better Emma Stone is raw and revelatory as Riggan's embittered daughter, fresh out of rehab and eager to hook Dad on social media, where quality is gauged by Facebook 'Likes.'

The very real achievement of Birdman, a dark comedy of desperation buoyed by Iñárritu's unbridled artistic optimism, is how it makes us laugh out loud, curse the shadows and see ourselves in the fallibly human Riggan. Birdman spins you around six ways from Sunday. It's an exhilarating high. No true movie lover would dare miss it.", ratings: "#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(30..50)}")

Review.create(critic: Critic.find(3), event: Event.find(2), content: "In “Birdman or The Unexpected Virtue of Ignorance,' Michael Keaton plays an actor named Riggan Thomson, who first appears hovering several inches above his dressing room floor, deep in meditation. He’s trying to ignore the voice of the title character, his alter ego, who takes the form of the comic book character he once played and whose superpowers he now seems able to conjure at the drop of a black leather cowl.

'How did we end up here?' Birdman growls in a sotto-voce whisper. 'This place is horrible.' After a few more profane put-downs, 'this place' is revealed to be backstage at New York’s St. James Theatre, where Thomson is directing and starring in an ambitious — and no doubt profoundly ill-advised — adaptation of a Raymond Carver short story. As if that bid for artistic legitimacy isn’t freighted enough, Thomson also is trying to grapple with the personal life he neglected for years while pursuing fame in Hollywood, including his fractured relationship with his daughter, Sam (Emma Stone), a new girlfriend (Andrea Riseborough) and his ex-wife, Sylvia (Amy Ryan), who pops in and out of his preparations for opening night like an even-tempered, clear-thinking visitor from another, far more self-aware planet.

From this setup alone, 'Birdman' has all the trappings of a deliciously tawdry backstage satire on a par with 'All About Eve' and 'Sweet Smell of Success,' but writer-director Alejandro González Iñárritu throws in a delightfully wacky monkey wrench in the form of a pretentious actor named Mike Shiner (Edward Norton), who’s cast in the play at the last minute when a member of the ensemble is injured (with or without the help of Thomson’s Birdman-esque psychic gifts). The moment Shiner appears on the scene, the strutting and fretting are kicked up a notch, with Norton gleefully, even courageously, throwing himself into a performance that showcases the subtleties of acting nuance but also makes him look utterly ridiculous as a performer of surpassing arrogance and overweening vanity.

Narcissism, ambition, insecurity and the wages of celebrity are addressed in one fell swoop in 'Birdman,' which Iñárritu and his longtime cinematographer, Emmanuel Lubezki, have filmed to resemble one long, unbroken take — a stunt that results in a film of delicate, even balletic, grace and one that poetically captures Thomson’s own state of mind. Tuned in, hyper-aware, Thomson moves through the world on a different frequency than his peers, or so he thinks: Through just a few casual gestures — and in one eyepopping set piece — the complicated, contradictory headspace Thomson occupies becomes palpable and real. Once a superstar, now human scale, he walks the boards and Broadway streets like a hungry ghost, searching for the potency his cartoonish persona once conferred, while simultaneously trying to escape the culture of pandering and cynicism he helped to create.

As much fun as 'Birdman' is to watch from a sheer technical and aesthetic standpoint, it gains untold layers of meaning from the presence of Keaton, whose own career as the big-screen Batman that launched a never-ending franchise is clearly one of Iñárritu’s inspirations. As critical as “Birdman” is of the idea of the carefully calculated Hollywood comeback (and Lindsay Duncan as a vinegary critic delivers a soaring aria to that effect in one of the film’s best scenes), the film manages to be just that. Keaton’s performance, both as Thomson and the éminence grise hovering over his shoulder, is nothing short of a triumph — a quiet, un-showy one-man master class in humor, pathos, physical vulnerability and dimly dawning wisdom that seems always to be disappearing around one of the St. James’s labyrinthine corners.", ratings: "#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(30..50)}")

Review.create(critic: Critic.find(4), event: Event.find(2), content: "After a barrage of cinema brilliant, bizarre and occasionally boring, the New York Film Festival drew to a close this year with Alejandro González Iñárritu's Birdman: The Unexpected Virtue of Ignorance, which has been driving the internet into an anticipatory frenzy since its first trailer hit. It quick became my most anticipated movie of the year because it brought the spotlight back to an icon of my childhood, the one and only Michael Keaton. After a film fest that was studded with disappointments, I was a bit desperate for Birdman to live up to my expectations. Little did I expect it to far exceed them.

Michael Keaton shines as Riggan Thomson, an aging superhero-movie star whose glory days are decades behind him. Desperate to recapture recognition and relevance, Riggan sinks all his time, money, and energy into writing, directing and starring in a Broadway play adaptation of Raymond Carver’s What We Talk About When We Talk About Love, which is fast-approaching its opening night. But he's cracking under the pressure. A snarling voice whispers to him when he's alone. And when he's not alone, he's surrounded by conflict thanks to his uptight best friend/lawyer (Zach Galifianakis), his furious assistant/daughter (Emma Stone), his needy co-stars (Naomi Watts and Andrea Riseborough), and a loose canon Broadway star (Ed Norton).

There's an obvious setup for meta humor as Riggan could seem a doppelganger for Keaton. (One forged his reputation in Birdman action movies, the other in Batman action movies.) While that does add an element of excitement and potential text to the narrative, Iñárritu's real target is showbiz at large. No one is exempt from this smart and hilarious satire, not artists, fans, or critics. Birdman plants us in the St. James theater where Riggan's show will play, and weaves through its stages, stairwells, and riggings to shine a light on all the insanities and indignities inherent in production. But it also explores our deep need to create.

As his hero makes the leap from action movies to Broadway, Iñárritu takes a risky leap on his own, from dramas (Babel, Amores Perros, 21 Grams) to comedy. And he sticks the landing. Birdman blends its satire with whip-smart banter, surreal spectacles, and some remarkably honest moments of observational humor. Better yet, Birdman is not only fantastically funny, but also a feat of production.

As you may have heard, the film is shot as if continuous. Not in real time, mind you. The handheld camera flows out of dressings rooms, down hallways, through doorways, and sometimes swish-pans through time dissolves, resulting in nearly an entire film that looks like it's one take. In reality, this meant meticulously blocked scenes, and takes that went as long as ten minutes, making every error a potentially major one. And yet, Birdman is strong.

Naturally, there are some drawbacks to this approach. This way of shooting allows for no coverage, so much of the film is made of up close-ups and two-shots that are often more utilitarian than artistic. Likewise, certain scenes--like a same sex lip lock--must be kept whole even if they feel forced in their final execution. You'd think this approach would demand perfection, lest the flaws be evident. Birdman's execution is not perfect. But I'd actually argue there's some virtue in this approach that risks warts and all.

Looking at the lighting in the film is not something I often do on a first watch through. But with characters bobbing and weaving in and around St. James, the rigs used to light them are often in frame. However, these are not the ugly light kits you'd usually see on Hollywood sets. Instead, Iñárritu and his team got creative, planting bare light bulbs, lacing rails with blue LED lights, and placing ceilings with convenient florescent panels. The characters in Birdman are always thoughtfully lit, no matter where they wander. And while you might notice these bare bulbs, I suspect they are meant to draw our attention. Consider these the brushworks on Iñárritu's portrait of the joys and travesties of show biz.

There's a splendid lunacy to Birdman. It radiates with emotion and energy, spinning through its continuous editing style with an elegance and ego that is intoxicating. A jazzy drum score threads throughout, sometimes diegetic, sometimes not, always impactful. Its uneven rhythms fill you with a sense of excitement and anxiety, perfect for this playhouse fast approaching its make-it-or-break-it debut. And while Iñárritu will surely be a contender for Best Director honors, his cast deserves heaps of praise for being able to pull off such an unconventional and complicated endeavor.

Placed well outside the schlubby niche he's become known for, Zach Galifianakis is sharp and still quite funny as the relentlessly protective lawyer. Naomi Watts and Ed Norton share an explosive chemistry as warring co-stars/lovers, yet Norton is at his best when his egomaniac condescends to Riggan with slick and reckless lectures. But for all its showbiz snarking and outrageous gags, Birdman contains at its core a tender and eccentric father-daughter story that Emma Stone and Michael Keaton make unforgettable.

Stone is allowed to shed her nice girl shtick and smiles to dig into a bitter twenty-something who is in recovery and blames her too-absent celebrity dad for all her troubles. It's a role that could play as little more than cliché, but Stone brings enough street smarts and fragility to the part that her Sam is distinctive, challenging, and mesmerizing. But it is Keaton who owns this movie.", ratings: "#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(30..50)}")

Review.create(critic: Critic.find(5), event: Event.find(2), content: content_generator, ratings: "#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(30..50)}")

Review.create(critic: Critic.find(1), event: Event.find(3), content: "12 Years a Slave is based on the memoir of Solomon Northup (Chiwetel Ejiofor), a free black man and professional violinist from New York who, in 1841, gratefully accepted an offer of employment from two men, claiming to be fellow artists and members of a traveling circus. The morning after a night of fine dining and wining with the pair, Solomon awoke to a nightmare – discovering that he had been deceived, drugged, kidnapped and sold into slavery.

Unable to find any free person who might listen to his protests – or brave enough to risk their own safety by aiding him – Solomon experienced humiliation, physical brutality and even unexpected kindness, before he became the property of Mr. Edwin Epps (Michael Fassbender), a slave owner who prided himself on his ability to break the spirit of any rebellious servant on his plantation. However, even when faced with such insurmountable horror, a soul as strong and dignified as Solomon’s could not be shattered.

Directed by Steve McQueen (Hunger, Shame) and scripted by John Ridley (Red Tails), 12 Years a Slave is a well-crafted film that uses the topic of slavery in the pre-Civil War U.S. as a means for ruminating on the human condition. However, it fails to make a clear-cut statement about the slavery issue or provide new insight on that dark chapter in American history. And thus, because the film doesn’t blink an eye – when it comes to portraying the cruelty/violence committed against blacks in the Antebellum South – there are times when it feels like (put bluntly) the equivalent of “torture porn” made for arthouse moviegoers.

In the past, McQueen has also used larger subjects (the IRA Hunger Strike, modern sex disorders) to explore how what a person does and/or what others do to a person’s body affects their spirit. That question is again his true focus with 12 Years a Slave, but the decision to use Solomon Northup’s tale as a way to further explore the issue proves less effective at best, highly questionable at worst. As a result, the scenes that depict the dehumanizing nature of slavery are genuinely disturbing to watch, yet the film as a whole fails to offer the kind of personal and informative character study that would’ve made all the suffering portrayed more meaningful (from a discussion standpoint).

Rest assured, 12 Years a Slave is as gorgeously shot and visually-composed as McQueen’s past films; his frequent cinematographer Sean Bobbitt photographs the 19th-century South as a sweltering hell – characterized by fiery sunsets, treacherous bogs and sparse cotton fields – populated by Solomon, other slaves and their oppressors. Meanwhile, the editing choices made by McQueen and his trusted editor, Joe Walker, favor subtly when it comes to spacing out shots and/or scenes that parallel one another (for thematic effect). Similarly, much of Hans Zimmer’s score is quiet and gentle – save for an early sequence (where Solomon is transported South by ferry), when the score becomes as over-the-top ominous as would befit a horror movie.", ratings: "#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(30..50)}")

Review.create(critic: Critic.find(2), event: Event.find(3), content: "“12 Years a Slave” isn’t the first movie about slavery in the United States — but it may be the one that finally makes it impossible for American cinema to continue to sell the ugly lies it’s been hawking for more than a century. Written by John Ridley and directed by Steve McQueen, it tells the true story of Solomon Northup, an African-American freeman who, in 1841, was snatched off the streets of Washington, and sold. It’s at once a familiar, utterly strange and deeply American story in which the period trappings long beloved by Hollywood — the paternalistic gentry with their pretty plantations, their genteel manners and all the fiddle-dee-dee rest — are the backdrop for an outrage.

The story opens with Solomon (Chiwetel Ejiofor) already enslaved and cutting sugar cane on a plantation. A series of flashbacks shifts the story to an earlier time, when Solomon, living in New York with his wife and children, accepts a job from a pair of white men to play violin in a circus. Soon the three are enjoying a civilized night out in Washington, sealing their camaraderie with heaping plates of food, flowing wine and the unstated conviction — if only on Solomon’s part — of a shared humanity, a fiction that evaporates when he wakes the next morning shackled and discovers that he’s been sold. Thereafter, he is passed from master to master.

It’s a desperate path and a story that seizes you almost immediately with a visceral force. But Mr. McQueen keeps everything moving so fluidly and efficiently that you’re too busy worrying about Solomon, following him as he travels from auction house to plantation, to linger long in the emotions and ideas that the movie churns up. Part of this is pragmatic — Mr. McQueen wants to keep you in your seat, not force you out of the theater, sobbing — but there’s something else at work here. This is, he insists, a story about Solomon, who may represent an entire subjugated people and, by extension, the peculiar institution, as well as the American past and present. Yet this is also, emphatically, the story of one individual.

Unlike most of the enslaved people whose fate he shared for a dozen years, the real Northup was born into freedom. (His memoir’s telegraphing subtitle is “Narrative of Solomon Northup, a Citizen of New-York, Kidnapped in Washington City in 1841, and Rescued in 1853, From a Cotton Plantation Near the Red River, in Louisiana.”) That made him an exceptional historical witness, because even while he was inside slavery — physically, psychologically, emotionally — part of him remained intellectually and culturally at a remove, which gives his book a powerful double perspective. In the North, he experienced some of the privileges of whiteness, and while he couldn’t vote, he could enjoy an outing with his family. Even so, he was still a black man in antebellum America.", ratings: "#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(30..50)}")

Review.create(critic: Critic.find(3), event: Event.find(3), content: "While it is not the role of critics to tell people which films to see and which to avoid (audiences make those decisions for themselves), let me begin by saying that if you have any interest in cinema – or, for that matter, in art, economics, politics, drama, literature or history – then you need to watch 12 Years a Slave. If, as now seems possible, this very powerful film from British director Steve McQueen achieves a clean sweep in the forthcoming best picture categories, it will be a rare example of awards ceremonies getting it right.

That McQueen may be on the verge of becoming not only the first black film-maker to win an Oscar for best director, but the first to do so while in possession of a Turner prize, lends enough historical precedent to merit your attention. But more important is the reward of seeing an artist using the medium of film for its highest purposes: to elevate, educate and ultimately ennoble the viewer by presenting them with something that is visceral, truthful and electrifyingly 'real'.

Based on the 19th-century memoir of Solomon Northup (adapted here by screenwriter John Ridley), 12 Years a Slave follows the tribulations of an educated carpenter, musician and family man from New York state who, in 1841, was kidnapped and sold into slavery in the south – a shockingly common phenomenon. Stripped of his past, his identity and even (in the eyes of the law) his humanity, the renamed 'Platt' becomes the property of plantation owner Ford (Benedict Cumberbatch), whose comparatively benign and sympathetic demeanour belies his slaver status. But after incurring the ire of sadistic farmhand Tibeats (Paul Dano), 'Platt' is sold down the river to Epps (Michael Fassbender), a broiling cauldron of psychotic rage whose desire for slave girl Patsey (Lupita Nyong'o) appears to be pushing him ever further into an abyss of uncontrollable cruelty.

Despite McQueen's repeated assertion that he has no distinct 'style' (the functional marriage of form and content is everything), critics have identified recurring tropes in his feature films, such as the audaciously lengthy single takes of Hunger (the priest/prisoner interview) and Shame (Sissy's song), which appear talismanic. At a deeper level, there's a consistent interest in the punishment of the flesh that dates back to his early moving-picture projects (the wrestling/teasing of Bear) and underwrites each of his three feature films, in which bodies are variously starved, entangled and beaten in obliterating fashion. The stench of hanging and flogging that drifts in the steamy Louisiana air of 12 Years a Slave makes watching occasionally unbearable – I looked away more than once; not a criticism (we are worlds away from the exploitational tones of Django Unchained), more an acknowledgement of the film's awful raw power. One sequence in which Northup is strung up like some strange fruit from a tree while life on the plantation ambles on around him achieves a surreal intensity that recalls the haunting poetry of Terrence Malick's existential war movie The Thin Red Line.

Here, in a role that requires precise wordless expression (McQueen lingers long and often upon the face that becomes his clearest storytelling tool), Ejiofor proves himself a master of physical understatement, the clench of his teeth and slightest parting of the lips speaking volumes. His stance, too (from upright to bowed and beyond), is crucial, with Patricia Norris's costumes adding both mood and verisimilitude, while Sean Bobbitt's camera captures both the antebellum landscape beauty and horrifying human tragedy of the south, aided by very handsome production design.

12 Years a Slave is not an easy watch and nor should it be. But with the exception of a somewhat distracting third-act cameo by co-producer Brad Pitt, it is pitched pretty near perfectly in terms of sheer narrative craftsmanship. This is an important story, told with passion, conviction and grace. See it now.", ratings: "#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(30..50)}")

Review.create(critic: Critic.find(4), event: Event.find(3), content: "Soon after its world premiere last year, 12 Years a Slave was widely described as the best film that has yet been made about American slavery.
That’s a big claim — and, I believe, an accurate one — although it raises an interesting question. Where, exactly, is the competition?
The new film from the British director Steve McQueen is an adaptation of the memoirs of Solomon Northup, a freeborn black American family man from upstate New York who was kidnapped, shipped to the South and sold to the owner of a Louisiana plantation in 1841. There have been other films about American slaves, and films that have described or depicted the American slave trade in some way too: not many, but enough high-profile ones, from Gone With the Wind all the way to Mandingo, for the topic not to feel like unmapped territory.
But films that are actually about American slavery are vanishingly rare — films that unpick slavery’s all-debasing power-plays, enumerate its everyday horrors, show us the rhythms and rituals that have left it lingering in that nation’s muscle memory. McQueen’s picture, nominated for 10 Baftas this week with Oscars sure to follow, does all of this, and could be the first of a new genre.

Solomon is played by Chiwetel Ejiofor: an enormously talented English actor getting the right break at the ideal moment. In the film’s early scenes, we watch Solomon stroll around his home town of Saratoga with his wife (Kelsey Scott) and children, and, Ejiofor moves with a gentle confidence that makes his later imprisonment seem not just inhuman, but illogical.

A year ago almost to the day, I wrote in the Telegraph about Quentin Tarantino’s Django Unchained: another film centred on a slave’s survival in the antebellum South. I loved Tarantino’s picture, but the two films can’t be sensibly compared. Django’s most startling scenes come glazed with irony, and it ends with a cathartic bloodbath that allows us to leave the cinema feeling that justice, of a limited sort, has been served. McQueen is working with no such protection.
To measure the importance of this we must go back to 1915. That year saw the release of D.W. Griffiths’ The Birth of a Nation: the historical epic, set during the American Civil War and its aftermath, that inscribed the rules that govern to this day how films are built, watched and loved. It was a smash hit. Its importance cannot be overstated. It was the first film to be screened in the White House, and Woodrow Wilson, the then-President, called it “history written with lightning”.
But Griffiths’ film has almost no truth in it — and it is monstrously, numbingly racist. Its black characters are drunks and rapists, played by gurning white actors in blackface, while the Ku Klux Klan are shown to be saviour knights of the new republic. Think again of that strange lack of films about American slavery, and wonder how long it will take for cinema to exorcise these demons. In that light, 12 Years a Slave isn’t simply a masterpiece, it’s a milestone. This, at last, really is history written with lightning.", ratings: "#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(30..50)}")

Review.create(critic: Critic.find(5), event: Event.find(3), content: content_generator, ratings: "#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(30..50)}")

Review.create(critic: Critic.find(1), event: Event.find(4), content: "At one point in “Argo,” a smart, jittery thriller about a freakish and little-known chapter of the Iranian hostage crisis, a Hollywood producer says that history starts as farce and ends up as tragedy. He seems, as someone rightly points out, to have it backward. But as a professional dissembler, he knows better. Because much like the revolutionary shock troops who seized the United States embassy on Nov. 4, 1979, and turned the crisis into gripping political theater watched by the entire world — tune in tomorrow when America goes on trial, with the special guest star the Ayatollah Khomeini — the producer knows that historical events alone don’t cut it. You need lights, camera, action.

Turning history into farce probably wasn’t what Antonio J. Mendez, a Central Intelligence Agency officer, was after when he was tapped to help free six State Department employees stranded in Tehran. While revolutionary forces were overrunning the embassy and taking hostages, including the 52 men and women who were held for 444 days, five Americans fled undetected. Eventually, they made their way to safety, including at the Canadian ambassador’s house, staying hidden (with a sixth escapee) while the C.I.A., the State Department and the president struggled to find a way to ferry them home. Mr. Mendez, a wizard of disguise, came up with the cover story for the six escapees that improbably stuck: They would pose as a Canadian movie crew.

It’s a doozy of a story and so borderline ridiculous that it sounds — ta-da! — like something that could have been cooked up only by Hollywood. Ben Affleck, however, who directed “Argo” from a script by Chris Terrio and cast himself in the pivotal role of Tony Mendez, realized that comedy alone wouldn’t do. American lives, after all, were at stake (a situation that contemporary viewers will be all too familiar with), and so, after opening the movie with a bit of history and archival imagery, he rushes into the moment’s jarring, unsettling craziness with a cinematic whoosh. Fast and faster, he sets the skittish stage with convincing you-are-there re-creations and then jumps back and forth between the chanting, exultant Iranian protesters outside the embassy and the freaked-out Americans inside it.

Mr. Affleck, working from Mr. Mendez’s book, “The Master of Disguise,” and a 2007 Wired magazine article, “The Great Escape,” by the journalist Joshuah Bearman, embellishes the official story without eviscerating it. Given how great the very premise is, it makes sense to stick more or less to the official record — a series of photographs from the hostage crisis that is juxtaposed with stills from the movie show how close Mr. Affleck hews to the evidence — and he and his production team clearly had fun with the Chia Pet facial hair, oversize glasses, wide collars, fat ties and earth-toned threads. Shrewdly, he visually transmits the escalating claustrophobia of the escapees’ confinement with billowing cigarette smoke, small rooms, a limited palette and shallow depth of field.

Mr. Affleck handles his own roles, on camera and behind it, with a noticeable lack of self-aggrandizement. He doesn’t show off with his direction or the performances, going for detail instead of bombast with eerie silences, traded glances, trembling gestures and beaded sweat. (It’s a good guess that he’s committed the unnerving opening of “Three Days of the Condor” to memory.) His own delivery can be so tamped down that he sometimes registers as overly restrained, almost bland, yet his control serves the material, partly because it would have been a mistake for him to try to upstage this story, much less Mr. Goodman and Mr. Arkin. And then, in the end, this is a story about outwitting rather than killing the enemy, making it a homage to actual intelligence and an example of the same.", ratings: "#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(30..50)}")

Review.create(critic: Critic.find(2), event: Event.find(4), content: "It's the same the world over. A Hollywood production comes to town, and the locals all turn movie crazy. When a little picture named 'Prancer' came to Three Oaks, Mich., I was sitting in the bar and overheard one bearded regular confide in his friend, 'See that guy? He's assistant makeup.'

  As in Michigan, so in Iran. At the height of the 1979 Iranian hostage crisis, with yellow ribbons tied around half the old oak trees in America, a CIA agent and a couple of Hollywood professionals dreamed up a cockamamie scheme to free six Americans who had found refuge in the Canadian embassy. Their existence had to remain a secret to protect Canada's diplomatic status.

Enter the CIA 'extractor' Tony Mendez (Ben Affleck), a producer named Lester Siegel (Alan Arkin) and a makeup man named John Chambers (John Goodman). Chambers has a brainstorm: He and Siegel would fabricate a fake sci-fi thriller named 'Argo.' They would commission a screenplay, pay for storyboards, and buy a big ad in Variety. Mendez would fly alone into Tehran and train the six Americans to impersonate Hollywood pros — the cinematographer and so on.

Their cover: They need desert locations for their movie, which would vaguely resemble 'Star Wars.' They would tell the Iranians the six people were Canadians who were scouting locations and now need to fly back to North America. One of the most enchanting scenes has Mendez showing the sci-fi storyboards to Iranian authorities, who try their best to conceal what movie buffs they are. At the end of the scene, when Mendez tells them 'you can keep em,' they're like kids being given an 'E.T.' poster by Steven Spielberg.

This preposterous scheme is based on fact. Yes, it is. Countless movies are 'inspired by real events,' but this one truly took place. The extraction of the six Americans remained top secret for 18 years. They all returned safely to America. 'Argo,' needless to say, was never filmed.

Ben Affleck not only stars in but also directs, and 'Argo,' the real movie about the fake movie, is both spellbinding and surprisingly funny. Many of the laughs come from the Hollywood guys played by Goodman and Arkin, although to be sure, as they set up a fake production office and hold meetings poolside at the Beverly Hills Hotel, they aren't in danger like their 'crew members' in Iran.

Key supporting roles are filled by Bryan Cranston, as the CIA chief who green-lights the scheme, and Victor Garber, as the Canadian ambassador who at great risk opens his embassy's doors to the secret guests. Affleck is brilliant at choreographing the step-by-step risks that the team take in exiting Tehran, and 'Argo' has cliff-hanging moments when the whole delicate plan seems likely to split at the seams.

The craft in this film is rare. It is so easy to manufacture a thriller from chases and gunfire, and so very hard to fine-tune it out of exquisite timing and a plot that's so clear to us we wonder why it isn't obvious to the Iranians. After all, who in their right mind would believe a space opera was being filmed in Iran during the hostage crisis? Just about everyone, it turns out. Hooray for Hollywood.", ratings: "#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(30..50)}")

Review.create(critic: Critic.find(3), event: Event.find(4), content: "Ben Affleck's dynamite new film Argo isn't just a tense, impeccably acted thriller, but fulfills some core purpose of Hollywood filmmaking that's practically been forgotten. Filmed on a modest budget, featuring a massive cast of familiar and likable faces, and telling a big story with maximum efficiency and entertainment value, Argo is the kind of serious drama that leaves you smiling because of how marvelously well it pulls everything off. It leaves the daring to the plot itself and allows the crackerjack precision of the story be what blows you away.

Taking the lead role as CIA extraction expert Tony Mendez, Affleck is an all-business type of spy, but brings with him a kind of stoic, inherent likability that's more familiar from his buddy Matt Damon in the Bourne movies. He's charged with staging the rescue of six Americans who escaped the embassy in Tehran, Iran when it was taken over by protesters in 1979, hiding out at the Canadian Ambassador's home. Along with his friend John Chambers (John Goodman), a Hollywood makeup artist, Mendez cooks up a fake movie production based on a sci-fi script called Argo, which they'll use as cover to extract the six Americans from Iran. With a crotchety producer (Alan Arkin) there to give the fake story weight, and a fellow CIA guy (Bryan Cranston) helping sell it to the top brass, the 'Argo' plan is sold as 'The best bad idea we've got.' And it works.

It takes a long time to set up pieces of a plan this elaborate, but Affleck opens the film with a vivid, terrifying depiction of the embassy takeover in Tehran, then segues effortlessly into the comic efforts to set up the fake production of Argo in Hollywood, complete with a table read and women dressed up as intergalactic babes. Chris Terrio's script transitions fluidly from Los Angeles back to Washington D.C. and over to Tehran, where the Americans dubbed the 'houseguests' cope with frazzled nerves and the ambassador (Victor Garber) because increasingly concerned that they're putting him at risk. Though the Hollywood scenes contain the biggest laughs (and Arkin gets all the best lines), there's humor included in nearly every scene, building character and adding audience investment into the story until it's time for the tense machinery of the great escape to be set in motion.

The many whirring pieces of the plot click into gorgeous synchronicity as the escape begins, with lots of familiar faces back at the CIA (Chris Messina, Zelijko Ivanek, Titus Welliver) keeping the operation running, the houseguests (among them Tate Donovan, Scoot McNairy and Clea DuVall) swallowing their fear, and Mendez at the center of it all keeping a cool head and an implacable stare. Affleck does such a good job of establishing the many dangers in Tehran, from hot-headed guards at the airport to the maid at the Canadian Embassy (Sheila Vand) under pressure to sell out the houseguests, that every step of the escape feels like a minefield, the tension ratcheted up deliciously. The audience I saw the film with spontaneously applauded at one key moment-- if there's better evidence for how expertly a film can play an audience, I don't know it.

Made with brisk confidence and technical precision, Argo is a spy thriller of a buttoned-up old school variety; we're not given a lot of emotional attachments to these characters, and the reward for a job well done is a pat on the back, not an explosion of grateful tears. But Argo is so sure-footed that it picks you up and carries you along with it anyway. If you are a lover of Hollywood movies at their best, the emotional catharsis of Argo isn't what happens onscreen, but the sheer knowledge that the creaky old moviemaking system has put together something this crowd-pleasing and great. ", ratings: "#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(30..50)}")

Review.create(critic: Critic.find(4), event: Event.find(4), content: "Hollywood has always been partial to a good old spy yarn, especially since the genre’s paranoiac, post-Watergate ’70s heyday. It also enjoys taking sideways glances at its own garish reflection (cf. The Player, Wag The Dog, State And Main). So, once the relevant CIA documents became declassified in 1997, revealing the stunning, real reason for a certain Star Wars rip-off once hyped in the pages of Variety never getting greenlit, Argo (working title Escape From Tehran) was surely a cinematic inevitability. It is a great ‘weirder than fiction’ story. One, in fact, that was the subject of a feature in this very magazine almost five years ago. Although, if you’d told us then that its adaptation would star and be directed by Ben Affleck rather than George Clooney (then attached, now only a producer), we’d have been as disbelieving as if you’d told us, pre-declassification, the very facts of this strange case.

To be fair, Affleck’s impressive directorial debut, Gone Baby Gone, was then already in the can and earning approving nods in press-screening rooms. But neither that nor even his follow-up, The Town — another strong Boston-based crimer — necessarily proved an aptitude for international period-nailing dramas, let alone one, oddly, with a virtually comedic middle act and a difficult climax. Yet here we are, just as Awards Season 2012 is warming up and the glowing late-summer festival reviews have poured in. It is hard to imagine Clooney, either in front of or behind the camera, doing a better job.

The Affleck of Argo couldn’t be further removed from the hunk that cried crocodile tears and jutted his mandible for Michael Bay all those years ago. Perhaps his ultimately embarrassing travails in the BGBG (Before Gone Baby Gone) Era fed usefully into Argo. You can imagine a crooked smile springing up on that square jaw as he pored over newcomer Chris Terrio’s snappy script and clocked the zinger, “You could teach a rhesus monkey to be a director in a day.”

Such bon mots are largely growled by Alan Arkin as (fictional) fading producer Lester Siegel, recruited by the CIA via amiable make-up genius John Chambers (John Goodman, playing the man who won an Oscar for his work on Planet Of The Apes) to set up the fake space opera that would provide the cover story for the Agency’s Tehran-based exfiltration operation. The Hollywood segment must have appealed to Affleck, and Clooney before him, as much for its outcome as for its breezy, self-deprecatory tone: this was a rare occasion where movies helped save the day for real, and where success went entirely unnoticed.

You can’t begrudge Affleck giving himself the ‘hero’ role of Company man Tony Mendez, because in a sense it’s the most thankless. He’s a hunched, unshaven, bleary-eyed, rumpled-shirted schlub, a man who wakes up in the morning fully clothed, surrounded by empty Chinese food cartons. He has no big, shouty-speech moment, despite his earnest conviction during the early CIA scenes that the “Hollywood option” is the best on offer. He simply moves quietly around the story’s dramedic triangle.

At one corner are the Tinseltown antics of Arkin and Goodman. At another are the CIA office scenes, headed up by Bryan Cranston as Mendez’ boss, who gets all the great lines not spoken by Arkin, including the film’s finest: “This is the best bad idea we have, sir.” And then there is the sharpest vertex, involving the six American consular officers holed up at the Canadian diplomat’s residence, whose journey takes them from narrowly escaping their embassy’s fall to having to swallow Mendez’ plan, which involves each of them pretending to be a department head of a non-existent B pic, who have simply visited the country for a recce.

It’s here that we find the film’s strongest performance, delivered by Monsters and Killing Them Softly’s Scoot McNairy, half-buried beneath bottle-glass peepers and a thick lip-brush. The CIA has predicted that his older colleague Bob Anders (Tate Donovan) will assume leadership of the group, but in fact it’s McNairy’s previously unassuming Joe Stafford who exhibits the most mettle under these nerve-twanging circumstances. When Mendez lays out his crazy scheme, it is Stafford who balks. In other hands this might have made him the, ‘Oh, just shuddup!’ guy; the twitchy doubter who in an Irwin Allen disaster movie would buy it at around the 70-minute mark. But McNairy and Affleck ensure that during their confrontations, it is with Stafford the sympathies lie. He’s not wrong: the plan was nuts. He is the clearest thinking, most emotionally honest and relatable person here.

Argo, really, is a series of balancing acts. One virtuoso sequence begins with a freaky-ludicrous public casting call, attended by various Hollybozos in sparkly motley. As these blithe, cut-price Threepios, Mings and Flashes launch into a script-reading while champagne flutes tinkle and cameras flash, Affleck intercuts with a chilling scene of trussed American hostages being hustled to a dank basement with sacks over their heads, where they are treated to a mock execution by the Iranian Revolutionary Guards, their knees buckling as rifle hammers dully snap down. This could jar horribly, but it works: the sense here is that everyone is putting on a show. The CIA, in putting on a fake movie junket. Hollywood, because, well, that is its very business. And the Khomeini-supporting Iranians, proving to a decadent world that they are not to be taken lightly.

The theme pulls the film neatly together and gives it thrilling impetus when it could so easily have stalled: during the final act. The truth is, there wasn’t a particularly dramatic denouement to the real events, but writer Terrio and Affleck here embellish the facts sensitively and effectively, among other things giving McNairy his glory moment as he hastily has to pitch this so-called “cosmic conflagration”, complete with comic-bookish storyboards, to an itchy-trigger-fingered Iranian soldier. Elsewhere, tried-and-tested tension-ramping techniques, while perhaps over-familiar, are applied judiciously, for example as the terrified sextet has to suffer a tour of Tehran’s bazaar in their flimsy show-people guises (Rory Cochrane’s faux-cinematographer looking through a viewfinder the wrong way) amid an increasingly ugly crowd; or when the irritating rhythms of movie production prove at one point to have potentially fatal consequences.

As Cranston’s character notes, there will be no applause for Mendez if his Escape From Tehran show is a success. But there will be for Affleck. And for a man shaping up to be one of America’s smartest mainstream drama directors, any ovations will be thoroughly deserved.", ratings: "#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(30..50)}")

Review.create(critic: Critic.find(5), event: Event.find(4), content: content_generator, ratings: "#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(30..50)}")

Review.create(critic: Critic.find(1), event: Event.find(5), content: "Is it possible to forget that 'The Artist' is a silent film in black and white, and simply focus on it as a movie? No? That's what people seem to zero in on. They cannot imagine themselves seeing such a thing. At a sneak preview screening here, a few audience members actually walked out, saying they didn't like silent films. I was reminded of the time a reader called me to ask about an Ingmar Bergman film. 'I think it's the best film of the year,' I said. 'Oh,' she said, 'that doesn't sound like anything we'd like to see.'

  Here is one of the most entertaining films in many a moon, a film that charms because of its story, its performances and because of the sly way it plays with being silent and black and white. 'The Artist' knows you're aware it's silent and kids you about it. Not that it's entirely silent, of course; like all silent films were, it's accompanied by music. You know — like in a regular movie when nobody's talking?

One of its inspirations was probably 'Singin' in the Rain,' a classic about a silent actress whose squeaky voice didn't work in talkies and about the perky little unknown actress who made it big because hers did. In that film, the heroine (Debbie Reynolds) fell in love with an egomaniacal silent star — but a nice one, you know? Played by Gene Kelly in 1952 and by Jean Dujardin now, he has one of those dazzling smiles you suspect dazzles no one more than himself. Dujardin, who won best actor at Cannes 2011, looks like a cross between Kelly and Sean Connery, and has such a command of comic timing and body language that he might have been — well, a silent star.

Dujardin is George Valentin, who has a French accent that sounds just right in Hollywood silent films, if you see what I mean. The industry brushes him aside when the pictures start to speak, and he's left alone and forlorn in a shabby apartment with only his faithful dog, Uggie, for company.

At a crucial moment, he's loyally befriended by Peppy Miller (Berenice Bejo), who when they first met, was a hopeful dancer and has now found great fame. The fans love her little beauty mark, which Valentin penciled in with love when she was a nobody.

As was often the case in those days, the cast of 'The Artist' includes actors with many different native tongues, because what difference did it make? John Goodman makes a bombastic studio head, and such familiar faces as James Cromwell, Penelope Ann Miller, Missi Pyle and Ed Lauter turn up.

At 39, Jean Dujardin is well-known in France. I've seen him in a successful series of spoofs about OSS 117, a Gallic secret agent who mixes elements of 007 and Inspector Clouseau. He would indeed have made a great silent star. His face is almost too open and expressive for sound, except comedy. As Norma Desmond, the proud silent star in 'Sunset Boulevard,' hisses: 'We didn't need dialogue. We had faces!' Dujardin's face serves perfectly for the purposes here. More than some silent actors, he can play subtle as well as broad, and that allows him to negotiate the hazards of some unbridled melodrama at the end. I felt a great affection for him.

I've seen 'The Artist' three times, and each time it was applauded, perhaps because the audience was surprised at itself for liking it so much. It's good for holiday time, speaking to all ages in a universal language. Silent films can weave a unique enchantment. During a good one, I fall into a reverie, an encompassing absorption that drops me out of time.

I also love black and white, which some people assume they don't like. For me, it's more stylized and less realistic than color, more dreamlike, more concerned with essences than details. Giving a speech once, I was asked by parents what to do about their kids who wouldn't watch B&W. 'Do what Bergman's father did to punish him,' I advised. 'Put them in a dark closet and say you hope the mice don't run up their legs.'", ratings: "#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(30..50)}")

Review.create(critic: Critic.find(2), event: Event.find(5), content: "While the movie industry abandoned black-and-white silent films 80 years ago, the spirit is of the past is back with writer/director Michel Hazanavicius's The Artist, a true crowd-pleaser that evokes the charm of old Hollywood.

Set in the late 1920s, the story centers on George Valentin (Jean Dujardin), a famous movie star who is truly on top of the world. His movies are some of the biggest in Hollywood and he is constantly surrounded by fans who heap praise upon him. One day, by pure chance, he meets a young background actor named Peppy Miller (Berenice Bejo), with whom he has an instant connection. What he doesn’t know is that their careers about to take completely opposite trajectories. Ignoring the trades and warnings from a powerful producer (John Goodman) that talkies are becoming the big thing, George refuses to change up his act, and watches his career sink lower and lower as Peppy rides the talkie wave and gets bigger and bigger.

Much like actors in early films, star Jean Dujardin must over-emote in order to compensate for his inability to express himself verbally. But in doing so, he puts on a marvelous performance. A challenging role, to say the least, Dujardin never pushes himself so far that it becomes hammy and we always know exactly how he feels and what’s going through his mind. What’s more, the French actor looks as though he’s been ripped straight out of the era, looking perfectly natural wearing a tailcoat tuxedo and sporting a pencil-thin mustache. He sells the drama, makes us laugh and is, in short, perfect as George Valentin.

The Artist presents George's life as the very kind of silent film he's trying to keep alive, allowing the audience to both re-discover the joys of silent film and fully understand George's plight. The character is so dead-set in his ways it would actually hurt the film to hear George speak, and The Artist allows the viewer to see George as though his entire life is a silent film, which is how he would actually prefer it. This is only reinforced by the fact that the first time we see the character is on screen and through the 1927 audience’s eyes. But he's so attached to his movie identity that his dog co-star is even with him in real life too performing little skits at the dinner table and acting like Lassie, rescuing George when he is in trouble (the dog’s performance is actually one of the film’s greatest highlights).

The silence is also used quite effectively in fun and creative ways. In a dream sequence early in the movie, George is stuck in a world filled with sound, but he himself cannot make any. In addition to foreshadowing his fate, the scene catches the audience by surprise, but isn’t disruptive or intrusive, just clever. Most importantly, the gimmick is used sparingly, which effectively makes each use of sound have more effect. When the element is reintroduced late in the film it manages to still feel fresh and impactful.

While the presentation and performances are terrific, The Aritst's derivative story prevents it from being a great film. The story of the silent film actor being pushed aside to make way for talkies is hardly new – one has to look no further than the 1950 Billy Wilder classic Sunset Blvd.. As a result, the whole thing smells of Michel Hazanavicius first deciding that he wanted to make a silent film and then finding the simplest story to tell in that format. This reverse engineering sadly dampens the film and while you can still have fun and feel for the main character, it’s never able to reach the heights that audiences may expect from it.

Despite its flaws, The Artist really is a delightful film. A love letter to an age of cinema gone by, it aims to reflect and recapture the spirit of some of the earliest films and does succeed in that regard. The movie isn’t revolutionary and doesn’t aim to create a whole new wave of silent filmmaking, but it is a fun diversion.", ratings: "#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(30..50)}")

Review.create(critic: Critic.find(3), event: Event.find(5), content: "Remember the old days, when movies were glorious, magical and mute? Neither do I. But the passing of the silent era from memory into myth is what “The Artist,” Michel Hazanavicius’s dazzling cinematic objet d’art, is all about. This is not a work of film history but rather a generous, touching and slightly daffy expression of unbridled movie love. Though its protagonist mourns the arrival of sound, “The Artist” itself is more interested in celebrating the range and power of a medium that can sparkle, swoon and suffer so beautifully that it doesn’t really need to have anything to say.

Strictly speaking Mr. Hazanavicius’s film is not a silent movie. There is a lot of music on the soundtrack and also a few strategic moments of onscreen noise that are both delightfully surprising and wildly illogical. The whole conceit of the picture is spun in willful disregard of the laws governing time, space and sound, an embrace of the preposterous that is perhaps more reminiscent of the spirit of early French cinema than of the old Hollywood where the action takes place.

In those days the sign up in the hills said HOLLYWOODLAND, and the screens were dominated by antic clowns, pale heroines and dashing lovers. George Valentin (Jean Dujardin, the star of the popular “OSS 117” series of French spy spoofs, also directed by Mr. Hazanavicius) undoubtedly belongs in that last category. With his shiny hair, radiant teeth and thin mustache — and a surname one vowel short of Valentino — George is a quintessential movie star. The public adores him, and he is far too gracious an entertainer to contradict them. A carefree narcissist, he bounces from the studio lot to the red carpet to the Beverly Hills mansion he shares with his devoted dog and less enchanted wife and co-star (Penelope Ann Miller), secure in the permanence of his glory.

Even viewers entirely innocent of film history — even the young, blockbuster-fed movie fans who find themselves dragged to and then transported by this minor marvel — will anticipate what happens next. George’s pride sets up a fall, first into a sweet, awkward infatuation with an aspiring actress named Peppy Miller (Bérénice Bejo), then into professional ruin brought about by his stubborn refusal to change with the times. Abandoned by his wife and shunned by the studio boss (a wonderfully boisterous John Goodman), with only the dog and his chauffeur (James Cromwell) standing by him, the star goes into eclipse. But even when threatened with the torments of obscurity, he refuses to speak.

The rise of the talkies has almost always been chronicled on film from the perspective of sound. It could hardly have been otherwise. “Singin’ in the Rain,” with its exuberant music and bright colors, does not so much revisit the old splendor of cinema silence as obliterate its memory, much as “Sunset Boulevard” unlocks a world of ghosts and shadows among the remnants of the faded Hollywood pantheon. “The Artist,” as aggressively entertaining as any musical, is measured in its mourning and eclectic in its nostalgia for old movies. There is a bit of music lifted from Bernard Herrmann’s “Vertigo” score, a breakfast-table montage inspired by “Citizen Kane” and a story line that makes “The Artist,” in essence, the latest (and also in a way the earliest, but surely not the last) remake of “A Star Is Born.”

Thanks in no small part to their expressiveness and dexterity — they dance beautifully and also portray emotion with just the right blend of naturalism and melodramatic exaggeration — “The Artist” is more than a clever pastiche of antique amusements. It may be something less than a great movie, but it is an irresistible reminder of nearly everything that makes the movies great.", ratings: "#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(30..50)}")

Review.create(critic: Critic.find(4), event: Event.find(5), content: "Michel Hazanavicius' black-and-white, mostly silent comedy The Artist is a gorgeously made curiosity -- a film that functions as a testament to its own obsession with other movies.

Hazanavicius has lovingly re-created the look, feel and rhythms of silent movies, from the 1.33:1 aspect ratio that renders the image a shimmering square on a modern-day rectangular screen, to the artfully designed intertitles that communicate what little dialogue there is. He also has conjured up a clever meta-story, with shades of Singin' in the Rain and A Star Is Born, about a silent-film star clinging to the past as Hollywood eagerly embraces the future.

Yet even if the film -- which earned six Golden Globe nominations and is expected to be a front-runner for the Best Picture Oscar -- sometimes threatens to turn into a postmodern hall of mirrors, it displays so much visual imagination, and Hazanavicius and his lead actors are so goofily zealous, that the effect is genuinely transporting.

For 100 blessedly low-key minutes, you get to leave the noise and rat-a-tat visual chaos of contemporary moviemaking far behind.

As the movie opens, in 1927, George Valentin (Jean Dujardin) is a winking narcissist, standing backstage as his latest silent-opus premiere to rapturous applause. With his pencil mustache and slicked back hair, he is meant to evoke any number of silent icons, like Rudolph Valentino (note the similarity of the last name) and John Gilbert. But even in the 1920s, the world is far more interested in celebrity than art.

The next morning the trades are filled not with gushing reviews, but photographs of George's accidental run-in, upon leaving the theater, with a would-be actress named Peppy Miller (Bérénice Bejo).

The fading star, the rising ingénue and the love that threatens to be extinguished by pride and ego -- the story of The Artist is as old as, well, silent movies. In short order, George is told by his producer (John Goodman) that the talkies are coming, a technology the star adamantly resists. Peppy, meanwhile, lands a gig as an extra, and then a bit player, eventually working her way up to a contract as a star player at the studio.

After George's wife (Penelope Ann Miller) leaves him, the actor sinks into a pit of bankruptcy and despair, with only his loyal chauffeur (James Cromwell) and Jack Russell terrier (Uggy, who steals even the scenes he isn't in) for companionship.

For the most part, The Artist succeeds in both winking at the audience and engaging us in the melodrama. Much credit for that goes to Dujardin and Bejo, who display such casual mastery of the silent movie acting vernacular -- the just-this-side-of-mugging facial expressions, the broad physical gestures -- that you invest in them as real people.

And Hazanavicius is a wonderfully clever showman, who keeps finding ways to inhabit both the past and the present simultaneously. In a dream sequence, for instance, George keeps hearing ambient sound, the stomping of feet or the laughter of women, but can't make any noise himself when he attempts to scream.

If The Artist never quite rises to the level of greatness, it's perhaps because Hazanavicius' approach is fundamentally self-conscious; he may love silent movies, but The Artist, by conceit, holds them at an arm's remove. The greatest silents, whether tragedies like F.W. Murnau's Sunrise (1927) or comedies like Buster Keaton's Steamboat Bill, Jr. (1928) still have a tremendous, almost primal emotional impact -- they get us right in the gut.

The Artist, on the other hand, is more clever than moving, more beguiling than substantive. When George's dog goes racing to save him from a burning house, you laugh at the wit and speed of the sequence -- but you also know it's a pastiche of silent movie conventions.

Lovely and charming as The Artist is, then, it finally comes off as a tad precious -- a movie about movies about movies; a true blast for film buffs that may leave everyone else scratching their heads.", ratings: "#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(30..50)}")

Review.create(critic: Critic.find(5), event: Event.find(5), content: content_generator, ratings: "#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(1..10)},#{rand(30..50)}")

Critic.create(username: "iank", email: "ian@ian.com", password: "password", profile_image: File.new("#{Rails.root}/public/profile.jpg"))
Review.create(event_id: 1, critic_id: 7, ratings: "", content: "")
